# Generated by Django 2.2.3 on 2019-07-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bought', models.DateField()),
                ('item', models.CharField(max_length=128)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('speed_of_sale', models.IntegerField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='item_images')),
            ],
        ),
    ]
