# Generated by Django 2.2.3 on 2019-07-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
