# Generated by Django 2.2.3 on 2019-07-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_auto_20190719_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='percent_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
