# Generated by Django 2.2.3 on 2019-07-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_auto_20190719_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='speed_of_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
